### ISSUE TITLE
Token storage bugfix (frontend)

### ISSUE THREAD

**Issue by eduong100** [grantKinsley/InventoryManagement#8]
We wish for tokens to persist even when the user closes the browser or changes the page. Therefore, configure for tokens to be stored and retrieved from local storage.

**Comment by grantKinsley** [comment]
currently implemented in the frontend branch using sessionStorage (similar to localStorage) where the JWT is cleared upon exiting the tab. A slightly more secure alternative in HTTP-only cookies can be implemented in the future, but this should now unblock #7
